services:
# mumureader 在线阅读
  mumureader:
    #image: mumujie/mumureader # 普通镜像
    image: mumujie/mumureader:openj9-latest # Openj9镜像，arm64架构或小内存机器优先使用
    container_name: mumureader #容器名 可自行修改
    restart: always
    ports:
      - 4396:8080 #4396端口映射可自行修改,8080请勿修改
    volumes:
      - ./logs:/logs #日志目录，相对于当前 Compose 文件
      - ./storage:/storage #数据目录，相对于当前 Compose 文件
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      #- READER_APP_USERLIMIT=50 #用户上限,默认且最大值为50
      - READER_APP_USERBOOKLIMIT=200 #用户书籍上限,默认200
      - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容
      - READER_APP_REMOTEWEBVIEWAPI=http://readerwebview:8050 #启用webview(若下方readerwebview容器不开启需注释此行
      # ↓多用户模式配置↓
      - READER_APP_SECURE=${READER_APP_SECURE:-true} #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_SECUREKEY=${READER_APP_SECUREKEY:?请在 .env 中设置管理员密码}
      - READER_APP_INVITECODE=${READER_APP_INVITECODE:-} #注册邀请码，可留空
# 如需支持webview书源，打开(占用较大，不需要可加 # 注释)
  readerwebview:
    image: hectorqin/remote-webview
    container_name: readerwebview
    restart: always
    environment:
      - TZ=Asia/Shanghai
