services:
# reader 在线阅读
  mumureader:
    image: mumujie/mumureader
    #image: mumujie/mumureader:openj9-latest #docker镜像，arm64架构或小内存机器优先使用此镜像.启用需删除上一行
    container_name: mumureader #容器名 可自行修改
    restart: always
    ports:
      - 4396:8080 #4396端口映射可自行修改
    networks:
      - share_net
    volumes:
      - ./logs:/logs #日志目录，相对于当前 Compose 文件
      - ./storage:/storage #数据目录，相对于当前 Compose 文件
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=50 #用户上限,默认50
      - READER_APP_USERBOOKLIMIT=200 #用户书籍上限,默认200
      - READER_APP_CACHECHAPTERCONTENT=true #开启缓存章节内容 V2.0
      # 如果启用远程webview，需要取消注释下面的 remote-webview 服务
      # - READER_APP_REMOTEWEBVIEWAPI=http://remote-webview:8050 #开启远程webview
      # 下面都是多用户模式配置
      - READER_APP_SECURE=${READER_APP_SECURE:-true} #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_SECUREKEY=${READER_APP_SECUREKEY:?请在 .env 中设置管理员密码}
      - READER_APP_INVITECODE=${READER_APP_INVITECODE:-} #注册邀请码，可留空
  # remote-webview:
  #   image: hectorqin/remote-webview
  #   container_name: remote-webview #容器名 可自行修改
  #   restart: always
  #   ports:
  #     - 8050:8050
  #   networks:
  #     - share_net
networks:
  share_net:
    driver: bridge
