services:
  reader:
    image: reader:pr701-local
    container_name: reader
    restart: always
    ports:
      - "4396:8080"
    volumes:
      - /home/reader/logs:/logs
      - /home/reader/storage:/storage
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERBOOKLIMIT=200
      - READER_APP_CACHECHAPTERCONTENT=true
      - READER_APP_SECURE=true
      - READER_APP_SECUREKEY=${READER_APP_SECUREKEY}
      - READER_APP_INVITECODE=${READER_APP_INVITECODE}
