name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    if: github.repository == 'xiamuceer-j/MuMuReader'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mumujie/mumureader
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        snapshot: true
        tags: "test"
